import './globals.css'
import { Fira_Sans, Anaheim } from '@next/font/google'

const firaSans = Fira_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-firaSans',
  weight: ['400','500','600','700']
})

const anaheim = Anaheim({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anaheim',
  weight: '400'
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${firaSans.variable} ${anaheim.variable}`}>{children}</body>
    </html>
  )
}
